"""diligent handoff command: paste-ready context document for AI sessions.

Generates a complete markdown document containing deal state for pasting
into a fresh AI session. Includes instruction header, deal context,
workstreams, recent truth facts, sources, open questions, stale artifacts,
and task summaries.
"""

import json
import os
import re
from datetime import date
from pathlib import Path
from string import Template
from typing import Optional

import click

from diligent.helpers.clipboard import copy_to_clipboard


_INSTRUCTION_TEMPLATE = Template("""\
# ${DEAL_CODE} Deal Context

This document was generated by **diligent**, a CLI tool for managing \
due diligence state. It captures the current state of deal analysis \
so you can resume work in this session.

**Key concepts:**
- **TRUTH.md** -- validated facts with sources and dates. Every fact has a source ID.
- **SOURCES.md** -- registered source documents (financial statements, contracts, etc.)
- **ARTIFACTS.md** -- deliverables (models, memos) that reference truth facts.
- **QUESTIONS.md** -- open and answered questions raised during diligence.
- **WORKSTREAMS.md** -- organizational spine connecting tasks, facts, and artifacts.

**Editorial principles:**
- Source every claim to a specific source ID. Do not invent values.
- Never fabricate data. If a number is not in the sources, say so.
- Flag discrepancies between sources rather than silently picking one.
- Do not use AI template phrasing. Write like a deal professional.

---""")


def _find_diligence_dir(env_cwd: Optional[str] = None) -> Path:
    """Locate the .diligence/ directory.

    Checks DILIGENT_CWD env override first (for testing), then walks
    up from cwd.

    Raises:
        click.ClickException: If .diligence/ not found.
    """
    if env_cwd:
        candidate = Path(env_cwd) / ".diligence"
        if candidate.is_dir():
            return candidate

    cwd = Path.cwd()
    for parent in [cwd] + list(cwd.parents):
        candidate = parent / ".diligence"
        if candidate.is_dir():
            return candidate

    raise click.ClickException(
        "No .diligence/ directory found. Run 'diligent init' first."
    )


def _build_instruction_header(deal_code: str) -> str:
    """Render the instruction header with deal code substitution."""
    return _INSTRUCTION_TEMPLATE.substitute(DEAL_CODE=deal_code)


def _build_deal_section(diligence: Path) -> str:
    """Build the ## Deal section from DEAL.md."""
    from diligent.state.deal import read_deal

    deal = read_deal(diligence / "DEAL.md")

    lines = ["## Deal", ""]
    lines.append(f"- **Deal Code:** {deal.deal_code}")
    lines.append(f"- **Target (Legal):** {deal.target_legal_name}")
    lines.append(f"- **Target (Common):** {deal.target_common_name}")
    lines.append(f"- **Stage:** {deal.deal_stage}")
    if deal.loi_date:
        lines.append(f"- **LOI Date:** {deal.loi_date}")
    lines.append(f"- **Principal:** {deal.principal} ({deal.principal_role})")
    lines.append(f"- **Seller:** {deal.seller}")
    lines.append(f"- **Broker:** {deal.broker}")
    if deal.thesis:
        lines.append("")
        lines.append(f"**Thesis:** {deal.thesis}")

    return "\n".join(lines)


def _build_workstreams_section(diligence: Path) -> str:
    """Build the ## Workstreams section from WORKSTREAMS.md."""
    from diligent.state.workstreams import read_workstreams

    ws_file = read_workstreams(diligence / "WORKSTREAMS.md")
    lines = ["## Workstreams", ""]

    for ws in ws_file.workstreams:
        status_label = f" ({ws.status})" if ws.status else ""
        lines.append(f"### {ws.name}{status_label}")
        if ws.description:
            lines.append(ws.description)
        lines.append("")

    return "\n".join(lines)


def _build_truth_section(diligence: Path, cutoff: date, everything: bool) -> tuple[str, list[dict]]:
    """Build the truth facts section filtered by time window.

    Returns (markdown_text, list_of_fact_dicts_for_json).
    Flagged facts are always included regardless of cutoff.
    """
    from diligent.helpers.time_utils import is_recent
    from diligent.state.truth import read_truth

    truth_path = diligence / "TRUTH.md"
    if not truth_path.exists():
        title = "## Truth (All)" if everything else "## Truth (Recent)"
        return f"{title}\n\nNo truth facts recorded.", []

    tf = read_truth(truth_path)

    title = "## Truth (All)" if everything else "## Truth (Recent)"
    lines = [title, ""]
    fact_dicts: list[dict] = []

    for key, fact in tf.facts.items():
        include = is_recent(fact.date, cutoff) or (fact.flagged is not None)
        if not include:
            continue

        flag_marker = " [FLAGGED]" if fact.flagged else ""
        lines.append(f"- **{key}**: {fact.value} (source: {fact.source}, date: {fact.date}){flag_marker}")
        if fact.flagged:
            lines.append(f"  - Flag: {fact.flagged.get('reason', 'no reason')}")

        fact_dicts.append({
            "key": key,
            "value": fact.value,
            "source": fact.source,
            "date": fact.date,
            "workstream": fact.workstream,
            "flagged": fact.flagged,
        })

    if not fact_dicts:
        lines.append("No facts in this window.")

    return "\n".join(lines), fact_dicts


def _build_sources_section(diligence: Path, cutoff: date) -> tuple[str, list[dict]]:
    """Build the sources section filtered by time window.

    Returns (markdown_text, list_of_source_dicts_for_json).
    """
    from diligent.helpers.time_utils import is_recent
    from diligent.state.sources import read_sources

    sources_path = diligence / "SOURCES.md"
    if not sources_path.exists():
        return "## Sources (Recent)\n\nNo sources registered.", []

    sf = read_sources(sources_path)
    lines = ["## Sources (Recent)", ""]
    source_dicts: list[dict] = []

    for src in sf.sources:
        if not is_recent(src.date_received, cutoff):
            continue

        parties_str = ", ".join(src.parties) if src.parties else "none"
        lines.append(f"- **{src.id}**: {src.path} (received: {src.date_received}, parties: {parties_str})")
        source_dicts.append({
            "id": src.id,
            "path": src.path,
            "date_received": src.date_received,
            "parties": src.parties,
        })

    if not source_dicts:
        lines.append("No sources in this window.")

    return "\n".join(lines), source_dicts


def _build_open_questions_section(diligence: Path) -> tuple[str, list[dict]]:
    """Build open questions section. Always included regardless of date.

    Returns (markdown_text, list_of_question_dicts_for_json).
    """
    from diligent.state.questions import read_questions

    questions_path = diligence / "QUESTIONS.md"
    if not questions_path.exists():
        return "## Open Questions\n\nNo questions recorded.", []

    qf = read_questions(questions_path)
    open_qs = [q for q in qf.questions if q.status == "open"]

    lines = ["## Open Questions", ""]
    question_dicts: list[dict] = []

    for q in open_qs:
        lines.append(f"- **{q.id}** [{q.workstream}] (owner: {q.owner}): {q.question}")
        question_dicts.append({
            "id": q.id,
            "question": q.question,
            "workstream": q.workstream,
            "owner": q.owner,
        })

    if not question_dicts:
        lines.append("No open questions.")

    return "\n".join(lines), question_dicts


def _build_stale_artifacts_section(diligence: Path) -> tuple[str, list[dict]]:
    """Build stale artifacts section. Always included regardless of date.

    Returns (markdown_text, list_of_stale_dicts_for_json).
    """
    from diligent.helpers.reconcile_anchors import compute_staleness
    from diligent.state.artifacts import read_artifacts
    from diligent.state.sources import read_sources
    from diligent.state.truth import read_truth

    artifacts_path = diligence / "ARTIFACTS.md"
    truth_path = diligence / "TRUTH.md"

    if not artifacts_path.exists() or not truth_path.exists():
        return "## Stale Artifacts\n\nNo artifacts registered.", []

    af = read_artifacts(artifacts_path)
    tf = read_truth(truth_path)

    sources_path = diligence / "SOURCES.md"
    sources = []
    if sources_path.exists():
        sf = read_sources(sources_path)
        sources = sf.sources

    stale_results = compute_staleness(af.artifacts, tf.facts, sources)

    lines = ["## Stale Artifacts", ""]
    stale_dicts: list[dict] = []

    for sa in stale_results:
        if not sa.is_stale:
            continue

        total_changed = len(sa.value_changed) + len(sa.source_superseded)
        all_info = sa.value_changed + sa.source_superseded
        max_days = max((info.days_stale for info in all_info), default=0)

        changed_keys = [info.key for info in sa.value_changed + sa.source_superseded]
        lines.append(f"- **{sa.path}**: {total_changed} facts changed, {max_days}d stale (keys: {', '.join(changed_keys)})")

        stale_dicts.append({
            "path": sa.path,
            "workstream": sa.workstream,
            "facts_changed": total_changed,
            "days_stale": max_days,
            "changed_keys": changed_keys,
        })

    if not stale_dicts:
        lines.append("No stale artifacts.")

    return "\n".join(lines), stale_dicts


def _build_workstreams_json(diligence: Path) -> list[dict]:
    """Build workstream data for JSON output."""
    from diligent.state.workstreams import read_workstreams

    ws_file = read_workstreams(diligence / "WORKSTREAMS.md")
    return [
        {"name": ws.name, "status": ws.status, "description": ws.description}
        for ws in ws_file.workstreams
    ]


def _build_task_summaries_section(diligence: Path) -> tuple[str, list[dict]]:
    """Build task summaries section from active workstream task dirs.

    For each workstream, scans tasks/ for subdirectories and finds the most
    recent SUMMARY.md with content. Returns (markdown_text, list_of_dicts_for_json).
    """
    from diligent.state.workstreams import read_workstreams

    ws_file = read_workstreams(diligence / "WORKSTREAMS.md")
    lines = ["## Recent Task Summaries", ""]
    summary_dicts: list[dict] = []

    for ws in ws_file.workstreams:
        if ws.status != "active":
            continue

        tasks_dir = diligence / "workstreams" / ws.name / "tasks"
        if not tasks_dir.exists():
            continue

        # Scan for task directories, sorted by name descending (most recent first)
        task_dirs = sorted(
            [d for d in tasks_dir.iterdir() if d.is_dir()],
            key=lambda d: d.name,
            reverse=True,
        )

        for task_dir in task_dirs:
            summary_path = task_dir / "SUMMARY.md"
            if not summary_path.exists():
                continue

            content = summary_path.read_text(encoding="utf-8").strip()
            if not content:
                continue

            # Strip HTML comments and check for real content
            stripped = re.sub(r"<!--.*?-->", "", content, flags=re.DOTALL)
            content_lines = [
                line for line in stripped.splitlines()
                if line.strip() and not line.strip().startswith("#")
            ]
            if not content_lines:
                continue

            lines.append(f"### {ws.name}: {task_dir.name}")
            lines.append("")
            lines.append(content)
            lines.append("")

            summary_dicts.append({
                "workstream": ws.name,
                "task": task_dir.name,
                "content": content,
            })
            break  # Only most recent per workstream

    if not summary_dicts:
        lines.append("No task summaries available.")

    return "\n".join(lines), summary_dicts


@click.command("handoff")
@click.option("--since", "since_str", default=None, help="Time window: '7d', '14d', or ISO date")
@click.option("--everything", is_flag=True, default=False, help="Include all entries regardless of date")
@click.option("--clip", is_flag=True, default=False, help="Copy output to clipboard")
@click.option("--json", "json_mode", is_flag=True, default=False, help="Output as JSON")
@click.pass_context
def handoff_cmd(ctx, since_str, everything, clip, json_mode):
    """Generate a paste-ready context document for AI handoff."""
    env_cwd = os.environ.get("DILIGENT_CWD")
    diligence = _find_diligence_dir(env_cwd)

    # Read config for default window
    from diligent.state.config import read_config
    from diligent.state.deal import read_deal
    from diligent.helpers.time_utils import parse_since

    config_path = diligence / "config.json"
    if config_path.exists():
        config = read_config(config_path)
        default_days = config.recent_window_days * 2
    else:
        default_days = 14

    # Determine cutoff date
    if everything:
        cutoff = date(2000, 1, 1)
    else:
        cutoff = parse_since(since_str, default_days)

    # Read deal for instruction header
    deal = read_deal(diligence / "DEAL.md")

    # Build all sections
    header = _build_instruction_header(deal.deal_code)
    deal_section = _build_deal_section(diligence)
    workstreams_section = _build_workstreams_section(diligence)
    truth_md, truth_data = _build_truth_section(diligence, cutoff, everything)
    sources_md, sources_data = _build_sources_section(diligence, cutoff)
    questions_md, questions_data = _build_open_questions_section(diligence)
    stale_md, stale_data = _build_stale_artifacts_section(diligence)
    summaries_md, summaries_data = _build_task_summaries_section(diligence)

    # JSON mode
    if json_mode:
        data = {
            "instruction_header": header,
            "deal": {
                "deal_code": deal.deal_code,
                "target_legal_name": deal.target_legal_name,
                "target_common_name": deal.target_common_name,
                "deal_stage": deal.deal_stage,
                "loi_date": deal.loi_date,
                "thesis": deal.thesis,
            },
            "workstreams": _build_workstreams_json(diligence),
            "truth": truth_data,
            "sources": sources_data,
            "open_questions": questions_data,
            "stale_artifacts": stale_data,
            "task_summaries": summaries_data,
        }
        output = json.dumps(data, indent=2, default=str)
    else:
        # Assemble full markdown output
        sections = [
            header,
            "",
            deal_section,
            "",
            workstreams_section,
            "",
            truth_md,
            "",
            sources_md,
            "",
            questions_md,
            "",
            stale_md,
            "",
            summaries_md,
        ]
        output = "\n".join(sections)

    # Always print to stdout
    click.echo(output)

    # Clipboard
    if clip:
        success = copy_to_clipboard(output)
        if success:
            click.echo("Copied to clipboard.", err=True)
        else:
            click.echo("Clipboard not available on this system", err=True)
